# Generated by Django 5.1 on 2024-08-09 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('IS_EQUAL', 'Is equal'), ('IS_DIFERENT', 'Is diferent'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not contains')], max_length=50)),
                ('value', models.TextField()),
                ('conditional_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.question')),
                ('primary_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='surveys.question')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='surveys.option')),
            ],
            options={
                'unique_together': {('question', 'value')},
            },
        ),
    ]
