# Generated by Django 5.1 on 2024-08-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_surveyquestion_survey_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['page_number', 'order']},
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
