# Generated by Django 5.1 on 2024-08-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_rename_is_definition_survey_is_only_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyinheritance',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
