# Generated by Django 5.1 on 2024-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_option_order_alter_surveyinheritance_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='parent_surveys',
        ),
        migrations.AddField(
            model_name='survey',
            name='child_surveys',
            field=models.ManyToManyField(related_name='parent_surveys', through='surveys.SurveyInheritance', to='surveys.survey'),
        ),
    ]
