# Generated by Django 5.1 on 2024-08-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_remove_survey_parent_surveys_survey_child_surveys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('order',)},
        ),
    ]
