# Generated by Django 5.1 on 2024-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_alter_option_order_alter_surveyinheritance_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyinheritance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='surveyinheritance',
            name='child_survey',
        ),
        migrations.RemoveField(
            model_name='surveyinheritance',
            name='parent_survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='child_surveys',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_only_child',
        ),
        migrations.AddField(
            model_name='option',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='reusable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='SurveyInheritance',
        ),
    ]
