# Generated by Django 5.1 on 2024-08-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_surveyinheritance_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='amount',
            new_name='goal',
        ),
    ]
