# Generated by Django 5.1 on 2024-08-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_alter_option_options_alter_option_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version_name', models.CharField(max_length=25)),
                ('version_code', models.SlugField(max_length=25)),
                ('body', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('survey', 'version_code')},
            },
        ),
    ]
