# Generated by Django 5.1 on 2024-08-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_surveyversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyversion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='surveys.survey'),
        ),
    ]
