# Generated by Django 5.1 on 2024-08-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_alter_surveyversion_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
    ]
