# Generated by Django 5.1 on 2024-08-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_alter_option_goal_alter_question_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('IS_EQUAL', 'Is Equal'), ('IS_DIFERENT', 'Is Diferent'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains')], max_length=50),
        ),
    ]
