# Generated by Django 5.1 on 2024-08-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_condition_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='goal',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
